# Generated by Django 4.1.5 on 2023-01-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('Department', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=500)),
            ],
        ),
    ]
